"""empty message

Revision ID: 49d47b6834a9
Revises: af21bd5c9d6e
Create Date: 2021-03-27 10:23:37.910405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49d47b6834a9'
down_revision = 'af21bd5c9d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('Users', 'create_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Users', 'timestamp')
    # ### end Alembic commands ###
