"""empty message

Revision ID: 66e585c1a78f
Revises: f7ff0bb3ef19
Create Date: 2021-03-27 15:03:16.021483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e585c1a78f'
down_revision = 'f7ff0bb3ef19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_type', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('emi', sa.Float(), nullable=False),
    sa.Column('total_payable_amount', sa.Float(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_Users_email', table_name='Users')
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.create_index('ix_Users_email', 'Users', ['email'], unique=True)
    op.drop_table('Loans')
    # ### end Alembic commands ###
