"""empty message

Revision ID: f7ff0bb3ef19
Revises: b71cff8fde86
Create Date: 2021-03-27 11:31:00.062901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ff0bb3ef19'
down_revision = 'b71cff8fde86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('public_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'Users', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'public_id')
    # ### end Alembic commands ###
