"""empty message

Revision ID: a8d8d4d96f6a
Revises: 66e585c1a78f
Create Date: 2021-03-27 21:46:23.837331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d8d4d96f6a'
down_revision = '66e585c1a78f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Loan_update_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_loan_id', sa.Integer(), nullable=True),
    sa.Column('loan_type', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_loan_id'], ['Loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Loan_update_history')
    # ### end Alembic commands ###
